[package]
name = "dicon-nifti-formatting"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "convert-nifti-to-dat"
path = "src/main.rs"

[dependencies]
ndarray = "0.15.6"
nifti = "0.15.0"
serde = {version = "1.0.160", features = ["derive"]}
serde_json = "1.0.96"
