on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  release:
    name: create release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: true
      - name: build
        run: cargo build --release
      - name: create GitHub release
        run: |
          mv target\release\convert-nifti-to-dat.exe .
          7z.exe a dicon-nifti-formatting-${{ steps.get_version.outputs.tag }}.zip convert-nifti-to-dat.exe example-options.json
          gh release create v${{ steps.get_version.outputs.tag }} dicon-nifti-formatting-${{ steps.get_version.outputs.tag }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}